import React from 'react';
import { StyleProp, ViewStyle } from 'react-native';

export type SFSymbolName =
  | 'flame.fill'
  | 'flame'
  | 'dumbbell.fill'
  | 'dumbbell'
  | 'archivebox.fill'
  | 'archivebox'
  | 'applewatch'
  | 'calendar'
  | 'calendar.badge.clock'
  | 'chart.line.uptrend.xyaxis'
  | 'chart.line.downtrend.xyaxis'
  | 'drop.fill'
  | 'drop'
  | 'fork.knife'
  | 'apple.intelligence'
  | 'sparkles.bubble.fill'
  | 'bell.fill'
  | 'bell'
  | 'clock.fill'
  | 'clock'
  | 'sparkles'
  | 'chevron.right'
  | 'chevron.left'
  | 'chevron.down'
  | 'chevron.up'
  | 'arrow.left'
  | 'arrow.right'
  | 'arrow.up'
  | 'arrow.down'
  | 'checkmark'
  | 'checkmark.circle.fill'
  | 'checkmark.circle'
  | 'checkmark.shield.fill'
  | 'xmark'
  | 'xmark.circle.fill'
  | 'xmark.circle'
  | 'plus'
  | 'plus.circle.fill'
  | 'square.and.pencil'
  | 'pencil'
  | 'pencil.line'
  | 'mic.fill'
  | 'mic'
  | 'bolt.fill'
  | 'bolt'
  | 'bolt.slash.fill'
  | 'trash.fill'
  | 'trash'
  | 'lock.fill'
  | 'lock'
  | 'envelope.fill'
  | 'envelope'
  | 'person.crop.circle'
  | 'person.crop.circle.fill'
  | 'person.2.fill'
  | 'mappin.and.ellipse'
  | 'camera.fill'
  | 'camera'
  | 'magnifyingglass'
  | 'line.3.horizontal'
  | 'house.fill'
  | 'house'
  | 'trophy.fill'
  | 'heart.fill'
  | 'heart'
  | 'waveform.path.ecg'
  | 'shield.fill'
  | 'shield'
  | 'shield.lefthalf.filled.trianglebadge.exclamationmark'
  | 'timer'
  | 'repeat'
  | 'arrow.clockwise'
  | 'arrow.counterclockwise'
  | 'arrow.triangle.2.circlepath'
  | 'clock.arrow.circlepath'
  | 'scalemass.fill'
  | 'scalemass'
  | 'barcode.viewfinder'
  | 'slider.horizontal.3'
  | 'leaf.fill'
  | 'leaf'
  | 'leaf.arrow.triangle.circlepath'
  | 'lightbulb.fill'
  | 'lightbulb'
  | 'wifi.slash'
  | 'phone.fill'
  | 'phone'
  | 'photo.fill'
  | 'photo'
  | 'doc.text.fill'
  | 'doc.text'
  | 'questionmark.circle.fill'
  | 'questionmark.circle'
  | 'exclamationmark.circle.fill'
  | 'exclamationmark.circle'
  | 'rectangle.portrait.and.arrow.right'
  | 'play.fill'
  | 'play'
  | 'target'
  | 'bookmark.fill'
  | 'bookmark'
  | 'list.bullet'
  | 'chevron.left.forwardslash.chevron.right'
  | 'note.text';

export interface SFSymbolProps {
  name?: SFSymbolName | string;
  size?: number;
  color?: string;
  fill?: string;
  strokeWidth?: number;
  style?: StyleProp<ViewStyle>;
  weight?: 'ultraLight' | 'thin' | 'light' | 'regular' | 'medium' | 'semibold' | 'bold' | 'heavy' | 'black';
}

export type SFSymbolIcon = React.FC<SFSymbolProps>;

// Backward-compatibility alias for screens/components previously referencing LucideIcon
export type LucideIcon = SFSymbolIcon;
